#!/usr/bin/python3
import sys
import urllib.request
import json

DISCORD_WEBHOOK_URL = ''

argv = sys.argv


def send_message_discord(message):
    url = DISCORD_WEBHOOK_URL
    method = 'POST'
    json_data = json.dumps({
        "content": message
    }).encode("utf-8")
    headers = {"User-Agent": "urllib.request",
               "Content-Type": "application/json"}
    request = urllib.request.Request(
        url, data=json_data, headers=headers, method=method)
    isError = False
    try:
        res = urllib.request.urlopen(request)
    except urllib.error.HTTPError as e:
        print('Error: HTTPError' + '(' + str(e.code) + ')', file=sys.stderr)
        isError = True
    except urllib.error.URLError as e:
        print('Error: URLError', file=sys.stderr)
        isError = True
    except:
        isError = True
    else:
        res.close()
    if isError:
        sys.exit(1)


if len(argv) == 2:
    message = argv[1]
    send_message_discord(message)
else:
    print('Error: invalid parameter', file=sys.stderr)
    sys.exit(1)
